### ISSUE TITLE
Firefox 57 shows standard Firefox new tab page upon startup instead of the humble one

### ISSUE THREAD

**Issue by still-dreaming-1** [ibillingsley/HumbleNewTabPage#48]
When Firefox 57 first starts up with the default settings, it shows the new tab page. But even with this extension installed, it does not show the custom one this extension provides, it shows the standard Firefox one. I'm using the Solus operating system if that makes any difference.

**Comment by frankyonnetti** [comment]
1. Open preferences in new window.
2. Open new (humble) tab in same window.
3. In preferences, under homepage, click on "Use Current Pages".

**Comment by still-dreaming-1** [comment]
@frankyonnetti that works thanks! I tried to do something similar before, but I could not find any URL to the humble tab page.

**Comment by still-dreaming-1** [comment]
I still would like this to be added as a feature. With the current solution offered, it eventually stops working, and I have to go through those steps over again, because the correct URL to get to that extension changes.

**Comment by still-dreaming-1** [comment]
It just happened again. The URL that would bring up the extension changed for some reason...
