### ISSUE TITLE
HNTP will not load when it's set up as the homepage in Firefox

### ISSUE THREAD

**Issue by Kurolox** [ibillingsley/HumbleNewTabPage#68]
I'm running on Firefox 67.0a1.

Trying to set up the HNTP page as the homepage in firefox will make it not render properly, leaving an empty white page rather than HNTP.

I'm using the method mentioned in https://github.com/quodroc/HumbleNewTabPage/issues/48 for setting the homepage. The URL I obtain is the following one:

`moz-extension://c822b406-0f1f-41cc-bad2-5a4c001090be/newtab.html`

Introducing said URL in the web browser will work properly. However, setting said URL as the homepage won't work properly.

I've disabled all other add-ons, but this behavior still happens.

**Comment by TCB13** [comment]
+1 on this.
