### ISSUE TITLE
other devices tab is empty

### ISSUE THREAD

**Issue by zhyiyu** [ibillingsley/HumbleNewTabPage#83]
My other devices tab is empty

<img width="207" alt="empty" src="https://user-images.githubusercontent.com/26550166/72286021-4dc09780-3612-11ea-80bd-f349e0488387.png">

despite the fact that I do have other devices

<img width="886" alt="devices" src="https://user-images.githubusercontent.com/26550166/72286068-5e710d80-3612-11ea-99b8-23d39954080b.png">

I recently switched to a new laptop, I am not sure if that is causing the problem.

Thanks!

**Comment by quodroc** [comment]
I think it requires having sync of "Open Tabs" enabled in your sync settings chrome://settings/syncSetup/advanced

**Comment by zhyiyu** [comment]
I think it is enabled

<img width="676" alt="sync" src="https://user-images.githubusercontent.com/26550166/72292775-1a850500-3620-11ea-9b4f-b9dffb8d77e8.png">

**Comment by zhyiyu** [comment]
I think "other devices" came back, it might just need a few weeks to get synchronized. Hope it could be a lot faster!
