### ISSUE TITLE
Zombie tabs when opening links into a Firefox Multi-Account Container

### ISSUE THREAD

**Issue by danielmmmm** [ibillingsley/HumbleNewTabPage#87]
This is a weird one: I have HNTP configured to open links in the current tab. However, sometimes a link seems to open in a new tab, leaving behind a blank zombie tab.

I found that the issue has to do with "Firefox Multi-Account Containers" and only occurs when other links are opened manually from within the HNTP tab.

1) Open a new HNTP tab
2) Right-click on any link and chose "open link in new tab"
3) Left-click on any link, that is configured to always open in "Firefox Multi-Account Containers"
=> step 3 leaves a blank tab behind

When I start with step 3), the link actually opens in the current tab.
When I click on a non-"Firefox Multi-Account Containers" link in step 3, it opens in the current tab.

**Comment by jest** [comment]
I can confirm this issue.

It wasn't a case about a year ago, as far as I remember, so this is probably an effect of changes in Firefox (as the extension hasn't been updated in last year).

**Comment by danielmmmm** [comment]
Oh my, this issue is old now :-)

This issue has a fix now:
Open the _Firefox Multi-Account Containers_ settings and click onto the _Options_ tab.
There, activate _Tab behaviour_ -> _Replace tab instead of creating a new one_.

This works well with _Firefox Multi-Account Containers_ v7.2.0 in Firefox v89.0.
